#!/bin/bash

# Install required yav bin
if [ -z "$(which yav)" ]; then
    if [[ -n $(which apt-get) ]]; then
        sudo apt-get install yandex-passport-vault-client
    elif [[ -n "$(which pip3)" ]]; then
        pip3 install yandex-passport-vault-client -i https://pypi.yandex-team.ru/simple
    else
        echo "yav is not found"
        exit 1
    fi
fi

# Replace {{sec-123 some_key}} with value from yav
function replace {
    FROM=$1
    TO=$2

    [[ -z "$FROM" ]] && return

    rm -f "$TO"

    while IFS= read -r LINE; do
        if [[ "$LINE" =~ \{\{(sec-.*)[[:space:]](.*)\}\} ]]; then
            VALUE=$(yav get version "${BASH_REMATCH[1]}" -o "${BASH_REMATCH[2]}")

            echo "${LINE/${BASH_REMATCH[0]}/$VALUE}" >> "$TO"
        else
            echo "$LINE" >> "$TO"
        fi
    done < "$FROM"
}

replace .env-template .env
